export const HDPI_FACTOR = window.devicePixelRatio
  ? window.devicePixelRatio
  : 2;
export const CANVAS_SIZE_RESOLUTION_INDEPENDENT = 300;
export const RESULT_SIZE_RESOLUTION_INDEPENDENT = 150;
export const CANVAS_SIZE = CANVAS_SIZE_RESOLUTION_INDEPENDENT * HDPI_FACTOR;
export const RESULT_SIZE = RESULT_SIZE_RESOLUTION_INDEPENDENT * HDPI_FACTOR;
